// <auto-generated />
using FullSearchApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

namespace FullSearchApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200605035452_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FullSearchApp.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abst")
                        .HasColumnName("abst")
                        .HasColumnType("character varying(512)")
                        .HasMaxLength(512);

                    b.Property<NpgsqlTsVector>("AbstVector")
                        .HasColumnName("abst_vector")
                        .HasColumnType("tsvector");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("character varying(128)")
                        .HasMaxLength(128);

                    b.Property<NpgsqlTsVector>("TitleVector")
                        .HasColumnName("title_vector")
                        .HasColumnType("tsvector");

                    b.HasKey("Id")
                        .HasName("pk_articles");

                    b.HasIndex("AbstVector")
                        .HasName("ix_articles_abst_vector")
                        .HasAnnotation("Npgsql:IndexMethod", "GIN");

                    b.HasIndex("TitleVector")
                        .HasName("ix_articles_title_vector")
                        .HasAnnotation("Npgsql:IndexMethod", "GIN");

                    b.ToTable("articles");
                });
#pragma warning restore 612, 618
        }
    }
}
